### Auth: login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "portals1234"
}

###

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODI3NGU4Nzc3OTcwZmNjMGFmMTZkZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NTQxNDI0NDksImV4cCI6MTc1NDIyODg0OX0.jva-qJ0O1Db3q-QdaLPElAZbfzLQCyC20j-sDcybklU

###

POST http://localhost:4000/api/notify/688e166b8e2ffead2db8b46f
Authorization: Bearer {{token}}
Content-Type: application/json

###

### 2. CREAR UN EQUIPO (usa {{token}})
POST http://localhost:4000/api/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Equipo REST",
  "players": ["Jugador1","Jugador2","Jugador3"],
  "contact": { "email": "rest@example.com" }
}

###

### 3. LISTAR EQUIPOS (usa {{token}})
GET http://localhost:4000/api/teams
Authorization: Bearer {{token}}